package com.luminex_studios.luminstatus;

import com.google.inject.Inject;
import com.luminex_studios.luminstatus.incident.IncidentManager;
import com.velocitypowered.api.command.CommandManager;
import com.velocitypowered.api.command.CommandMeta;
import com.velocitypowered.api.event.Subscribe;
import com.velocitypowered.api.event.player.KickedFromServerEvent;
import com.velocitypowered.api.event.proxy.ProxyInitializeEvent;
import com.velocitypowered.api.event.proxy.ProxyShutdownEvent;
import com.velocitypowered.api.plugin.Plugin;
import com.velocitypowered.api.plugin.annotation.DataDirectory;
import com.velocitypowered.api.proxy.ProxyServer;
import com.velocitypowered.api.scheduler.ScheduledTask;
import com.luminex_studios.luminstatus.command.StatusCommand;
import com.luminex_studios.luminstatus.config.StatusConfig;
import com.luminex_studios.luminstatus.health.HealthMonitor;
import com.luminex_studios.luminstatus.history.HistoryStore;
import com.luminex_studios.luminstatus.notify.DiscordNotifier;
import com.luminex_studios.luminstatus.update.SpigotUpdateChecker;
import com.luminex_studios.luminstatus.web.PagePublisher;
import com.luminex_studios.luminstatus.web.StatusHttpServer;
import com.luminex_studios.luminstatus.web.StatusSnapshot;
import org.slf4j.Logger;

import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.TimeUnit;

/**
 * LuminStatus: a public status page generated by the proxy itself.
 *
 * <p>The proxy is the only component that knows the whole internal picture. An
 * external uptime monitor can tell you the proxy port answers; it cannot tell
 * you that the survival backend is dead while the proxy cheerfully drops
 * everyone into the lobby. That is the gap this plugin fills.
 */
@Plugin(
        id = "luminstatus",
        name = "LuminStatus",
        version = LuminStatusPlugin.VERSION,
        description = "Generates a public status page for your network from the proxy's own view of it.",
        url = "https://github.com/lumin-mc/LuminStatus",
        authors = {"Lumin"}
)
public final class LuminStatusPlugin {

    public static final String VERSION = "v1.0.0";

    private final ProxyServer proxy;
    private final Logger logger;
    private final Path dataDirectory;

    private final List<ScheduledTask> tasks = new ArrayList<>();

    private volatile StatusConfig config;
    private HealthMonitor monitor;
    private HistoryStore history;
    private IncidentManager incidents;
    private StatusSnapshot snapshot;
    private PagePublisher publisher;
    private StatusHttpServer httpServer;
    private DiscordNotifier notifier;
    private SpigotUpdateChecker updateChecker;

    @Inject
    public LuminStatusPlugin(ProxyServer proxy, Logger logger, @DataDirectory Path dataDirectory) {
        this.proxy = proxy;
        this.logger = logger;
        this.dataDirectory = dataDirectory;
    }

    @Subscribe
    public void onProxyInitialize(ProxyInitializeEvent event) {
        try {
            config = StatusConfig.load(dataDirectory);
        } catch (Exception ex) {
            logger.error("Could not read config.conf. LuminStatus will not start; "
                    + "fix the file and restart the proxy.", ex);
            return;
        }

        history = new HistoryStore(dataDirectory, logger, config.history().retentionDays());
        history.load();

        incidents = new IncidentManager(dataDirectory, logger, config.history().retentionDays());
        incidents.load();

        monitor = new HealthMonitor(proxy, logger, history, config);
        monitor.syncComponents();

        notifier = new DiscordNotifier(config, logger);
        monitor.onStateChange((component, previous) -> notifier.queue(component, previous));

        snapshot = new StatusSnapshot(monitor, incidents, history);

        try {
            publisher = new PagePublisher(snapshot, incidents, config, logger);
        } catch (Exception ex) {
            logger.error("Could not load the bundled page template. LuminStatus will not start.", ex);
            return;
        }

        httpServer = new StatusHttpServer(publisher, logger);

        updateChecker = new SpigotUpdateChecker(logger, "LuminStatus", VERSION,
                config.updateChecker().resourceId());

        CommandManager commands = proxy.getCommandManager();
        CommandMeta meta = commands.metaBuilder("luminstatus")
                .aliases("lstatus", "netstatus")
                .plugin(this)
                .build();
        commands.register(meta, new StatusCommand(this).build());

        startServices();

        logger.info("LuminStatus {} is watching {} server(s).", VERSION, monitor.components().size());
    }

    @Subscribe
    public void onProxyShutdown(ProxyShutdownEvent event) {
        stopServices();
        if (history != null) {
            history.save();
        }
        if (incidents != null) {
            incidents.save();
        }
    }

    /**
     * Records connection failures the proxy observes while routing real players.
     * This is free evidence and it reacts faster than the poll interval, which
     * matters most at the exact moment a backend dies.
     */
    @Subscribe
    public void onKickedFromServer(KickedFromServerEvent event) {
        if (monitor == null || !event.kickedDuringServerConnect()) {
            return;
        }
        monitor.recordPassiveFailure(
                event.getServer().getServerInfo().getName(),
                "connection rejected while routing a player");
    }

    // ------------------------------------------------------------- lifecycle

    private void startServices() {
        StatusConfig current = config;

        if (current.http().enabled()) {
            httpServer.start(current.http());
        }

        tasks.add(proxy.getScheduler().buildTask(this, () -> {
                    monitor.syncComponents();
                    monitor.runChecks();
                    notifier.flush(monitor.components());
                })
                .delay(2, TimeUnit.SECONDS)
                .repeat(current.monitoring().intervalSeconds(), TimeUnit.SECONDS)
                .schedule());

        tasks.add(proxy.getScheduler().buildTask(this, this::publishNow)
                .delay(5, TimeUnit.SECONDS)
                .repeat(current.staticExport().intervalSeconds(), TimeUnit.SECONDS)
                .schedule());

        tasks.add(proxy.getScheduler().buildTask(this, () -> {
                    history.prune();
                    history.save();
                    incidents.prune();
                })
                .delay(5, TimeUnit.MINUTES)
                .repeat(5, TimeUnit.MINUTES)
                .schedule());

        if (current.updateChecker().enabled() && current.updateChecker().resourceId() > 0) {
            tasks.add(proxy.getScheduler().buildTask(this, () -> updateChecker.check())
                    .delay(30, TimeUnit.SECONDS)
                    .repeat(current.updateChecker().intervalHours(), TimeUnit.HOURS)
                    .schedule());
        }
    }

    private void stopServices() {
        tasks.forEach(ScheduledTask::cancel);
        tasks.clear();
        if (httpServer != null) {
            httpServer.stop();
        }
    }

    /**
     * Reloads the configuration in place.
     *
     * @return false when the new file could not be parsed, in which case the
     *         previous configuration stays active
     */
    public boolean reload() {
        StatusConfig loaded;
        try {
            loaded = StatusConfig.load(dataDirectory);
        } catch (Exception ex) {
            logger.error("Reload failed, keeping the previous configuration", ex);
            return false;
        }
        stopServices();
        config = loaded;
        monitor.applyConfig(loaded);
        notifier.applyConfig(loaded);
        publisher.applyConfig(loaded);
        updateChecker = new SpigotUpdateChecker(logger, "LuminStatus", VERSION,
                loaded.updateChecker().resourceId());
        startServices();
        publishNow();
        return true;
    }

    /** Re-renders the page and writes the static export if it is enabled. */
    public void publishNow() {
        if (publisher == null) {
            return;
        }
        publisher.refresh();
        StatusConfig current = config;
        if (current.staticExport().enabled()) {
            Path target = dataDirectory.resolve(current.staticExport().directory());
            publisher.exportTo(target);
        }
    }

    // --------------------------------------------------------------- accessors

    public StatusConfig config() {
        return config;
    }

    public HealthMonitor monitor() {
        return monitor;
    }

    public HistoryStore history() {
        return history;
    }

    public IncidentManager incidents() {
        return incidents;
    }

    public StatusSnapshot snapshot() {
        return snapshot;
    }

    public DiscordNotifier notifier() {
        return notifier;
    }

    public SpigotUpdateChecker updateChecker() {
        return updateChecker;
    }
}
